# docker-compose.yml file version
version: '2'
services:
  api:
    build: ./
    ports: 
      - "4200:4200"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
     - "27017:27017"
    volumes:
     - mongodata:/data/db 
volumes:
 mongodata:

    # volumes:
    #  - ~/data/study-express:/data/db
